### ISSUE TITLE
add ClearURLs type

### ISSUE THREAD

**Issue by vavavr00m** [collinbarrett/FilterLists#1081]
https://gitlab.com/KevinRoebert/ClearUrls/blob/master/data/data.min.json

**Comment by DandelionSprout** [comment]
Due to the *ClearURLs* extension only allowing one filterlist at a time with no option for custom entries, the severe difficulties I have in testing and writing new entries for it, and that its syntax is not used by any other extensions, I vote against including that syntax and extension at the moment.

**Comment by KevinRoebert** [comment]
The data.min.json is also used by [Uroute](https://github.com/walterl/uroute).

In a future release I will implement an interface to add custome rules and exceptions :)

**Comment by collinbarrett** [comment]
Are we proposing adding a new [Syntax](https://github.com/collinbarrett/FilterLists/wiki/Syntax) or [Software](https://github.com/collinbarrett/FilterLists/wiki/Software) or both? I'm cool with that. I'm not real familiar with the ClearURLs project.

**Comment by DandelionSprout** [comment]
My understanding from what I remember from back in October, was that it was both.

**Comment by collinbarrett** [comment]
I'm cool with adding a new Syntax and/or Software if we haven't already. Will defer to what @DandelionSprout thinks and if he wants to add them.

**Comment by DandelionSprout** [comment]
After trying out ClearURLs again after 7 months, it appears to me that the list in the OP is the only ClearURLs-format known to exist *and* is included by default in both ClearURLs and Uroute (The only known tools that can use that format), my (probably slightly overdue) conclusion is that there's no actual need to add this list, software nor syntax, because it'd offer nothing new to the users of any of those things.

**Comment by collinbarrett** [comment]
works for me. thanks for looking into it again. closing for now.
