### ISSUE TITLE
add property for confirmed software support

### ISSUE THREAD

**Issue by collinbarrett** [collinbarrett/FilterLists#11]
Add a property for signaling what software tools each list has been verified to support. For each list, provide a list of labels such as "uBlock Origin", "AdBlock Plus", etc. for software tools that the list has been confirmed to work with.

**Comment by Snapy** [comment]
Would be nice to do the same for incompatible software (i.e. lists in uAssets).

**Comment by collinbarrett** [comment]
@Snapy , can you explain what you mean further? I do not understand your suggestion. Thanks.

**Comment by Snapy** [comment]
Have a visual indication which indicates if a list is incompatible with a certain adblocker. For instance uBO supports [additional syntax](https://github.com/gorhill/uBlock/wiki/Static-filter-syntax) compared to ABP. It can also be [different](https://github.com/gorhill/uBlock/releases/tag/1.4.0) (first point).

**Comment by collinbarrett** [comment]
Right. Ok, I understand. Yes, that was my initial intention with this issue. I think, at least to start, I'll look at just adding another property to each list that has an array of adblocker software tools it can be used in. On FilterLists, then, these will be displayed as some sort of tags that can be sorted/filtered on. It would be nice to build out something automated in the future where FilterLists auto-determines what tools each list supports, but I think initially it will just have to be manual.

**Comment by Snapy** [comment]
This is essential in case it breaks the extension's functionality.

**Comment by bershan2** [comment]
I feel like there is a significant need for a list of all the network filters that support these lists.

How about creating a new file `data/software.json` for this? Also, you could give every extension a short tag (like "uBO" for uBlock Origin or "ABP" for Adblock Plus) and keep all information as a key-value pair like [built-in filter lists list in UBO](https://github.com/gorhill/uBlock/blob/master/assets/assets.json). Key-value pair structure would simplify lookup when collecting statistics. I'd like to help with that if you are interested in this. Also, this would allow to display a comprehensive software lists (table) under "Software Support" on About page (or taking that to a separate page).

If interested, which properties do you like to collect? I think (to start off) the current `data/filters.json` properties would be sufficient, except for minor changes:
* `list` being renames to `software`.
  Or even better `name` or `title` (because `name` or `title` obviously describes software if it is in `software.json`).
* `viewUrl` being substituted with something like a set of key-value pairs of `chromeUrl`, `safariUrl`, `firefoxUrl`, and `edgeUrl`, `iosUrl`.
* Property `related` could contain upstream projects or forks, then?

I imagine the entire thing would look like this (uBlock Origin picked as an example):
```
"uBO": {
  "name": "uBlock Origin",
  "descr": "uBlock Origin - An efficient blocker for Chromium and Firefox. Fast and lean.",
  "descrSourceUrl": "https://github.com/gorhill/uBlock",
  "homeUrl": "https://github.com/gorhill/uBlock",
  "issuesUrl": "https://github.com/gorhill/uBlock/issues",
  "forumUrl": "https://discourse.mozilla-community.org/t/support-ublock-origin/6746",
  "tagLang": [ (46 languages here) ],
  "donateUrl": "https://github.com/gorhill/uBlock/wiki/Why-don't-you-accept-donations%3F",
  "viewUrl": [
    "chromeUrl": https://chrome.google.com/webstore/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm",
    "firefoxUrl": "https://addons.mozilla.org/en-US/firefox/addon/ublock-origin"
  "related": ["(tag name of uBO for Microsoft Edge)", "(tag name of uBO for Safari (macOS))"]
  ]
}
```


Related: would greatly simplify issue `#63 Is a default in software` (not a link to avoid spamming).

**Comment by collinbarrett** [comment]
Definitely, that's exactly what I had planned to do at some point. Actually, I even had added a [stub](https://github.com/collinbarrett/FilterLists/commit/2ca923e6a51816a200075105a61a2a200f2b7a93) for this awhile back, but didn't have the time to work on it, so I think I removed it again for now (it was empty). 

I do love the idea of it being a separate entity/json file/db table. So, software.json would be great. I think the keys you fleshed out are great and would be a good starting point.

I'd definitely welcome any help you want to contribute! I'd love to give more to this project, my time is just limited right now. You could certainly help create the software.json file, but the front-end is currently WordPress (I'd love to replace that at some point). So, I don't think it'd be super easy for you to assist actually displaying the data from the new file on the website since that is not open-sourced in this repo, really... Open to any ideas, though.

**Comment by bershan2** [comment]
@collinbarrett I have a few questions that I will number for simplicity of referencing later.

1. I would like to move the future discussion of `data/software.json` to a separate issue. In fact, probably should not have commented here in the first place, but instead should have opened a new one and referenced this issue there. Just double-checking: **do you have an issue opened for that already?** If no, I'll open a new one, OK?
2. The logger is full of ideas about new properties (for `lists.json`), yet none of them are ever used. As far as I understand, addition of new properties should not break anything (because processing software should be clever enough to ignore them), so why don't you have a set of "test" properties -- the ones that you think are needed, but would not put on the main page yet. Am I wrong?
3. The site is static (or seems this way), so why did you choose WordPress if the project is on GitHub and you could use GitHub Pages for free and open up for community contributions? (Hosting would be free, but you would still have to pay DNS for `filterlists.com` domain if you don't like `*.github.io` domain name). I'm not suggesting to move, I'm just asking because I never used WordPress.

**Comment by collinbarrett** [comment]
Hi @bershan2 ,

1. Sure. Yes, since this issue is more for listing which tools are supported by each list. The software.json would be more for indexing all of the tools themselves. Feel free to open a new issue.

2. Sure, we can add more properties to the lists.json that are in-development. That would not break the current pipeline.

3. I actually started with WordPress, just because that is what I knew, before ever moving to GitHub. I would be fine with doing something like GitHub pages, I just do not have the front-end development skills to whip up the responsive grid, etc. And, my time is very limited at this point. If someone else wants to develop that front-end, I'd be more than happy to switch. Hosting costs are not a concern, though, since it is on a shared VPS that I use for a couple of other sites anyway.

**Comment by collinbarrett** [comment]
I think this is now being fully captured in the implementation for #7 . closing now as "duplicate", but let me know if it should be re-opened for any reason.
