### ISSUE TITLE
Invalid List "NoOnMe's List for Surge"

### ISSUE THREAD

**Issue by sr093906** [collinbarrett/FilterLists#1440]
see:

https://surge.noonme.com/surge.conf

**Comment by DandelionSprout** [comment]
I can only presume it's using a bunch of features that may or may not actually be exclusive to Surge.

And since Surge appears to be Apple-exclusive as per https://nssurge.com/, and is also designed to be a paid product, I can't test it out with any ease either.

I vote for keeping this issue report open until I can figure out more about Surge.

**Comment by sr093906** [comment]
> I can only presume it's using a bunch of features that may or may not actually be exclusive to Surge, to the detriment of other Socks5 tools.
> 
> And since Surge appears to be Apple-exclusive as per https://nssurge.com/, and is also designed to be a paid product, I can't test it out with any ease either.
> 
> I vote for keeping this issue report open until I can figure out more about Surge.

Thanks for reply. The list works again for now.
