### ISSUE TITLE
Help adding a filterlist (watchlist-internet.at)

### ISSUE THREAD

**Issue by stonecrusher** [collinbarrett/FilterLists#1663]
Hi!
The austrian government has an official place where they collect fraudulent domains.
I made a scraping script in python to convert those to [PiHole domain format](https://github.com/stonecrusher/filterlists-pihole/raw/master/watchlist-internet-ph.txt) and [uBO recommended format](https://raw.githubusercontent.com/stonecrusher/filterlists/master/watchlist-internet.txt) (which might not be necessary - it's just so you are able to temporarly disable the filter).
I wanted to make it available for others by listing it on your site.

Despite the wiki I am very unsure what to do and which IDs to choose in the data model. The metadata itself should be quite obvious: German language, Domain-only format, I am the maintainer but origin is from watchlist-internet.at
Any idea what would be best way to proceed?
Greetings, Stonecrusher

**Comment by collinbarrett** [comment]
Hey, sure. Sorry that it is difficult to add at the moment unless you are familiar with how we do things. The easiest place to start is just reply to this Issue with all of the relevant data about your list. Start [here](https://github.com/collinbarrett/FilterLists/wiki/FilterList). You can click [here ](https://github.com/collinbarrett/FilterLists/blob/master/data/FilterList.json) to see the existing data to get a feel for the data we have for other lists. We have a few folks who help out when they can taking new GitHub Issues and adding them to the site.

**Comment by DandelionSprout** [comment]
Normally, making use of the IDs that are in active use, here's normally how to do it:

1) Go to https://github.com/collinbarrett/FilterLists/blob/master/data/FilterList.json, right-click on "View raw", and choose Download.
2) Open Sublime Text (or Notepad++ or something similar).
3) Add a section near the bottom of the file and fill out "id", "description", "homeUrl", "issuesUrl", "licenseId", "name", "syntaxId" and/or "viewUrl" for the list; and save the file.
4) Due to GitHub's online editor only supporting files up to 1MB, we sadly have to assign the list's language before actually properly adding the lists. Thus, go to https://github.com/collinbarrett/FilterLists/edit/master/data/FilterListLanguage.json.
5) "listId" is the "id" from FilterList.json. "languageId" from is a randomly numbered list of languages at [Language.json](https://github.com/collinbarrett/FilterLists/blob/master/data/Language.json). German is 167, for the record.
6) When you've saved FilterListLanguage.json, this should usually create a fork at https://github.com/stonecrusher/FilterLists/tree/master.
7) Go to https://github.com/stonecrusher/FilterLists/tree/master/data and click "Upload", and upload FilterList.json that you edited a few minutes prior.
8) Submit the pull request, and me and/or Collin will double-check it from there.

**Comment by stonecrusher** [comment]
Thank you for your kind help guys, that's amazing.
It's much less complicated than I thought, just editing FilterListLanguage.json and FilterList.json; the other stuff is just for looking up IDs (or creating new, if necessary).
It might be worth linking this issue in the [readme](https://github.com/collinbarrett/FilterLists/#adding-or-updating-lists). The two links on the topic there are a bit overwhelming, although it's not hard to add a new list.

I made this PR: https://github.com/collinbarrett/FilterLists/pull/1668

Maybe it would be appropriate to create a new [tag](https://github.com/collinbarrett/FilterLists/blob/master/data/Tag.json) as the list is specialized in fraudulent sites and fake shops? I don't think it really fits in "malware". Or just no tag as most other lists.

**Comment by DandelionSprout** [comment]
For simplicity's sake, scam-specific lists are normally grouped under "phishing", though "malware" can also be used. I'll see if I can get this issue report added as a quick guide somewhere in the repo's instructions sometime this weekend.

**Comment by DandelionSprout** [comment]
Also, oh, I forgot to give instructions on how to add tags.

It's pretty much the same as steps 4-5 above, but with https://github.com/stonecrusher/FilterLists/edit/master/data/FilterListTags.json instead.

**Comment by stonecrusher** [comment]
I added the "phishing" tag in the PR. That matches quite good.   
Didn't have that keyword in my mind and must have overlooked it in the list. Thanks!

**Comment by collinbarrett** [comment]
Closed by #1668 . Thanks, @stonecrusher !

**Comment by collinbarrett** [comment]
And, thanks for helping as always, @DandelionSprout !
