### ISSUE TITLE
Removal of ABP-Japanese filters.

### ISSUE THREAD

**Issue by ryanbr** [collinbarrett/FilterLists#1737]
We should consider removing ABP-Japanese filters, as unsupported.

- **Aliexpress:** Anyone wanting to shop on Alixpress.com; [blocked outright](https://github.com/k2jp/abp-japanese-filters/blob/master/abpjf.txt#L7366) with `||aliexpress.com^`  [Requested removal ](https://github.com/k2jp/abp-japanese-filters/issues/56)in June 2019, No fix or acknowledgement. 

- **Youtube:** When Brave had to replace ABP-Japanese after it broke youtube: https://github.com/brave/adblock-lists/issues/355
Related report, ~3 months, No acknowledgement, no fix:   https://github.com/k2jp/abp-japanese-filters/issues/60
 
- **Apple:** Broken filter affecting apple.com [reported in Oct/2019](https://github.com/k2jp/abp-japanese-filters/issues/57), No fix or acknowledgement. 

The sites aren't minor, and we occasionally have issues with large sites also in Easylist. But we don't ignore users or requests.

Last commit update was in February, but regardless of this. Given the author unwilling to fix any issues, this list should never be used or promoted. It's damaging the user experience with adblockers.

**Comment by collinbarrett** [comment]
Thanks. I'm good with removing these.

I had hoped to add back better features around when a list was last updated, how frequently it's updated, and maybe some other measures of "quality" to help users be aware of things like this if they are referred to a list from FilterLists. But, I just haven't had the time to work on it yet.

**Comment by DandelionSprout** [comment]
Having thought about the matter for some hours while taking a nap, I think it deserves mention that even if we remove all that project's lists from FilterListsCOM (of which there's 4~7), it's [still a selectable included option in all AdGuard versions](https://github.com/AdguardTeam/FiltersRegistry/tree/master/filters/ThirdParty/filter_200_ABPJapaneseFilters), because AdGuard doesn't really remove old or bad lists that I know of; they just stamp them as outdated or problematic, while still offering them for easy use.

If we're planning to go full-on cancel culture on that list (Keep in mind I have only the faintest possible idea what that term means), we should at least get AdGuard to join us on it.

**Comment by collinbarrett** [comment]
Yeah, I'd ideally like to not remove the lists completely but add some sort of flag to users that they might not be ideal. Hmm... Agreed on AdGuard as well.

We don't have any automated or defined way of flagging lists of lower quality at the moment. We could add a manual tag as a quick/easy answer, but I'm _sure_ these aren't the only lists we have on FilterLists that would fall into this tag, and it'd be subjective and would require manual maintenance.

Something like #371 eventually... Man, I really wish I could carve out more time to add features.
