### ISSUE TITLE
482 returns null for viewUrl

### ISSUE THREAD

**Issue by gwarser** [collinbarrett/FilterLists#1916]
"Energized Blu Go. Another Lite Pack from Energized."

It has valid mirror URL - should probably be moved.

**Comment by DandelionSprout** [comment]
I see that at some point while I handled a whole lot of Energized list stuff, I accidentally used `"viewUrlMirror1"` instead of `"viewUrl"` in line 4925 of FilterList.json.

I have been told that there are currently huge database structure changes being worked on and implemented, and have been told to not make any PRs until I've been told it's done. So I can't take care of this right away, sadly.

**Comment by collinbarrett** [comment]
yep, the db changes are getting close. I'll take care of fixing this^ asap.
