### ISSUE TITLE
generic cdn domains

### ISSUE THREAD

**Issue by collinbarrett** [collinbarrett/FilterLists#209]
Lists that include generic cdn domains, like `d12ulf131zb0yj.cloudfront.net`, should receive a deduction in FilScore.

Per @Atavic [here](https://github.com/collinbarrett/FilterLists/issues/189#issuecomment-364801492).

**Weight:** Low

**Comment by Atavic** [comment]
The problem is that scripted subdomains as:

   **daq0d0aotgq0f**.cloudfront.net
   ...

   **pl109299**.puhtml.com
   **pl5411**.bntags.com

...are created for the very purpose of avoiding being blacklisted. The owners of **cloudfront**, **puhtml** & **bntags** have a script ready to put new subdomains online once the available old onews get too much blacklisting.

Solutions are list all the available domains, like [this filterlist](https://github.com/collinbarrett/FilterLists/issues/187) does with *admob*

>admob.com
admob.de
admob.biz
admob.co.uk
...

BTW there are worst cases like:

   a0675c1160de6c6.com
   476vi285.stream
   d50285bff60edbb406.com

...where even the whole domain is the result of a scripted registration.

**Comment by Atavic** [comment]
The problem is that scripted subdomains as:

    *daq0d0aotgq0f*.cloudfront.net
    ...

    *pl109299*.puhtml.com
    *pl5411*.bntags.com

...are created for the very purpose of avoiding being blacklisted. The owners of cloudfront, puhtml & bntags have a script ready to put new subdomains online once the available old onews get too much blacklisting.

A solution is to  list all the available domains, like [this filterlist](https://github.com/collinbarrett/FilterLists/issues/187) does with admob:

    admob.com
    admob.de
    admob.biz
    admob.co.uk
    ...

BTW there are worst cases like:

    a0675c1160de6c6.com
    476vi285.stream
    d50285bff60edbb406.com

...where the *whole domain* is the result of a scripted registration.

**Comment by Atavic** [comment]
Just another note, as seen on hosts2ch, there's a lazy scripted version, where

    rc.i2i.jp
    rc2.i2i.jp
    ...
    rc9.i2i.jp

has a clear imprinting, where no random value are used.

**Comment by Atavic** [comment]
Just another note, as seen on hosts2ch, there's a lazy scripted version, where

    rc.i2i.jp
    rc2.i2i.jp
    ...
    rc9.i2i.jp

has a clear imprinting, where no random values are used.

**Comment by elypter** [comment]
is there a way to filter those not by url but by the reference in the source html file?

**Comment by Atavic** [comment]
If you mean to inspect the code and modify the parts containing these urls, yes. Proxies do this e.g. [Fiddler](https://github.com/telerik/fiddler-docs/blob/e9d182b2403d5aee4cd8fe44e31d53dd319305ff/KnowledgeBase/FiddlerScript/ModifyRequestOrResponse.md) or Privoxy.

**Comment by Atavic** [comment]
Just another lazy scripted version:

    fra1.ib.adnxs.com
    fra1.mobile.adnxs.com
    fra10.ib.adnxs.com
    fra100.ib.adnxs.com
    fra11.ib.adnxs.com
    fra110.ib.adnxs.com

...that appears in this [hosts file](https://github.com/collinbarrett/FilterLists/issues/211).

**Comment by elypter** [comment]
cool. is it possible with an adblocker extension too? i dont know if they can intercept pageload early enough

**Comment by Atavic** [comment]
Yes, some modify redirections or User Agent, like https://github.com/FirefoxBar/HeaderEditor
But Webextensions - compared to old Addons - have reduced possibilities.

**Comment by collinbarrett** [comment]
closing into master issue #371
