### ISSUE TITLE
[JP] Warui Adhosts [114,000 URLS]

### ISSUE THREAD

**Issue by Atavic** [collinbarrett/FilterLists#211]
Description 	hosts by warui.intaa.net
(*Japanese list for AdAway, DNS66 - IPv4 - 114,000 urls*)

DescriptionSourceUrl 	https://warui.intaa.net/adhosts/
- DiscontinuedDate 	N/A 	#hosts by warui.intaa.net  *2018-02-12 04:11:44*
*Languages 	jp
*License 	N/A
*Maintainers 	Devs at https://warui.intaa.net/adhosts/
Name 	hosts by warui.intaa.net
(*Warui Adhosts*)
 
PolicyUrl 	N/A
SubmissionUrl 	N/A
*Syntax 	hosts.txt (0.0.0.0)
*UpstreamFilterLists

    hosts-file.net/ad_servers.txt
    pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&showintro=0&mimetype=plaintxt
    winhelp2002.mvps.org/hosts.txt
    adaway.org/hosts.txt
    someonewhocares.org/hosts/hosts

ViewUrl 	https://warui.intaa.net/adhosts/hosts.txt

- For *DiscontinuedDate* will re-check soon...

I created these two entries:
Description (*Japanese list for AdAway, DNS66 - IPv4 - 114,000 urls*)
Name (*Warui Adhosts*)
...as I can't read japanese.

**Comment by Atavic** [comment]
DiscontinuedDate is still *2018-02-12 04:11:44*

**Comment by collinbarrett** [comment]
That date looks like it was the last date the author said the list was updated. The "discontinuedDate" is for the date when the author declared the project dead. There are many lists that have not been updated in sometime that are "discontinued". I still want to list those as well, but clearly display that they have been inactive for some time. See new-ish documentation here: https://github.com/collinbarrett/FilterLists/wiki/FilterList

As far as the last updated date, I am working on a [service](https://github.com/collinbarrett/FilterLists/tree/master/src/FilterLists.Services/SnapshotService) that crawls the lists to decide when lists were actually last updated. Some lists, I have found, auto-update their date at the top of the file without actually updating any rules. Others use inconsistent date formatting or don't include a date at all. So, I'm going to let FilterLists' service decide when a list was updated rather than what is in the list header.

**Comment by Atavic** [comment]
Thanks for clearing.
