### ISSUE TITLE
English Language Tag Missing for Few Subscriptions 

### ISSUE THREAD

**Issue by Nzzyme** [collinbarrett/FilterLists#2132]
Currently, we do not see English tags for few subscriptions in the 'Language' column. Can you please include that? Thanks

**Comment by collinbarrett** [comment]
English is kind of considered the default if no other languages are specified. We have #269  to track adding the ability to filter the language column by no language tags. When we are able to get that feature in, that might help. I'm not sure we'll explicitly add an English tag to each list since I think it would apply to most.
