### ISSUE TITLE
update BadHosts

### ISSUE THREAD

**Issue by Atavic** [collinbarrett/FilterLists#245]
NOTE: The info I have to submit for adding this hosts file isn't clear to me...

HOME:
http://www.hostsfile.org/hosts.html

URL:
http://www.hostsfile.org/Downloads/BadHosts.msw.zip

**Comment by collinbarrett** [comment]
Thanks. I think I already have this one in the new dataset, though. Search `"id": 179,` [here](https://github.com/collinbarrett/FilterLists/blob/master/data/FilterList.json). Is there an update to the list info or a new list on the same site?

Closing for now, but will re-open if needed.

**Comment by Atavic** [comment]
Yes, it's that *id*
But the hosts file says that it integrates the PAC File from the same site. With no PAC there are some holes in it.

**Comment by collinbarrett** [comment]
I think indexing PAC files is currently out-of-scope for FilterLists. PAC files are more dynamic/code rather than simple one-liner rules. The description for this hosts file clearly states its designed to be used in conjunction with the PAC file. I think I'll leave this as is for now. Feel free to provide further feedback, though, and I'm happy to reconsider.
