### ISSUE TITLE
use browser back button to close modals and clear grid filters

### ISSUE THREAD

**Issue by elypter** [collinbarrett/FilterLists#250]
when clicking on details or when doing a search the url should include an anchor so when you hit back on the browser (eg: after viewing a list) you get back to the search or the details page instead of the main page.

**Comment by collinbarrett** [comment]
Are you referring to the [beta](https://beta.filterlists.com) site?

I agree. I have been trying to determine the best way to do this. I like the idea of popping up modals with details, but I also like the idea of details being separate canonical pages...

Can you elaborate on your idea a bit more? If there is another site that does something similar that you could share, that'd be helpful.

**Comment by elypter** [comment]
i havent read through this completely but it sounds promising https://css-tricks.com/using-the-html5-history-api/

**Comment by collinbarrett** [comment]
Since details are now expanders instead of modals, I don't think this is necessary any more. Back button to clear filters isn't necessarily an intuitive UX. It may be nice to have clear button(s) to clear filter boxes, but that's fairly low priority, I think.

Feel free to update if you disagree, but closing for now.
