### ISSUE TITLE
add a unique id to the subscribe button of each list

### ISSUE THREAD

**Issue by elypter** [collinbarrett/FilterLists#291]
i was wondering how to solve the problem of seeing which lists i am already subscribed to and came up with the solution to add a filter to the list that makes the subscribe button grey. here is an example for the blockhead list:
`##a[href="abp:subscribe?location=https%3A%2F%2Fraw.githubusercontent.com%2Felypter%2Ffilter_processor%2Fmaster%2Fgenerated_filterlists%2Fblockhead(decoy_generic_extraction).txt&amp;title=Blockhead%20(Generic%20Extraction%20Based)"]:style(background-color: #888888 !important;)`

it works but it is ugly and will fail if the download url changes. it would be easier to do this if each subscribe button has an id. it is not an optimal solution because everyone would have to include this in their filters and they should all use the same shade of grey but i thought it would be an easy solution.

**Comment by collinbarrett** [comment]
Interesting idea. I'll need to think on that a bit more. i definitely see what you are trying to accomplish, just trying to think if there is a bit more elegant way to implement it.

**Comment by DandelionSprout** [comment]
@elypter As for the lists that I've made, most of which are featured on FilterLists, I've currently opted to not add such grey-button entries to them, as I am currently worried that such entries would look a bit out of place to the uninitiated. Like they'd be thinking á la _"Why does the anti-malware list that I subscribe to have an entry for Filterlists.com"_?

But on the other hand, I am in reality writing this comment in order to personally thank you for making me aware of the _:style_ tag. Documentation on the many things that adblockers can do, tends to be scarce, incomplete and spread out, so it was thanks to your example line in the OP that I became aware that adblockers can change elements' CSS styles, which was even more critical for me to know about after I discovered that Stylish (An extension that's specifically about CSS modification) had been in some heavy privacy controversies and can't be installed on browsers anymore.

My [website stretcher list](https://raw.githubusercontent.com/DandelionSprout/adfilt/master/Dandelion%20Sprout's%20Website%20Stretcher.txt) for widescreen monitors couldn't have existed without you, and I thank you for it.

**Comment by elypter** [comment]
> I've currently opted to not add such grey-button entries to them, as I am currently worried that such entries would look a bit out of place to the uninitiated.

well, i understand. it's a hack. to make this work properly this would have to be integrated into an adblocker.

>My website stretcher list for widescreen monitors couldn't have existed without you, and I thank you for it.

thats a cool list. i also had a similar idea for a userscript that works with heuristics like blockhead. unfortunately this is not very performance efficient because the userscript has to loop over all elements. for this to work well i would need an interface to the adblocker so the script is only run if an element is detected that is worth further investigation and an interface to add rules to a list so the script only has to run once on a site. unfortunately i haven't found any adblocker yet who is willing to implement this.

**Comment by collinbarrett** [comment]
Closing as won't fix, but open to reconsider. I think the value-add is too low to justify. Implementation of #263, if/when it happens, could be helpful, though.

**Comment by collinbarrett** [comment]
Oh, also #112
