### ISSUE TITLE
add NSFW hosts 

### ISSUE THREAD

**Issue by KonoromiHimaries** [collinbarrett/FilterLists#306]
https://raw.githubusercontent.com/CyanideBrother/anti-pr0n/master/hosts
https://raw.githubusercontent.com/Clefspeare13/pornhosts/master/0.0.0.0/hosts
https://raw.githubusercontent.com/mhxion/pornaway/master/hosts/porn_sites.txt

**Comment by DandelionSprout** [comment]
Hi, @KonoromiHimaries. Have you ever tried to add the relevant details to the files yourself, through forking and pull requesting? While I can't speak for Collin or for the FilterLists project in any substantial capacity, it'd take up quite a bit of my freetime to look through all the lists and repos that you suggest, to find the needed information about licences, descriptions, list formats, etc.

If you were able to fill in the details yourself, which takes 5-10min per list, it'd presumably take a lot less time for Collin to then do the final adjustments and to accept the lists, which'd also mean that he'd be able to find the needed time to do so a lot sooner than he'd otherwise be.
