### ISSUE TITLE
various date questions

### ISSUE THREAD

**Issue by jawz101** [collinbarrett/FilterLists#326]
The website displays Added and Updated dates:
Added date seems irrelevant to anyone.
Updated Date- is this a last modified date or just the last time the file was touched?  I would think if you're actually seeing if the contents of the file have changed that would be more relevant.  If they're just continually replacing a file with the same contents then it really hasn't changed.

In the filterlist.json:

publishedDate:  None of the entries have them and I don't see why I'd need to know when it was created.  Are you expecting us to track down the lists date of inception?

Discontinued date: Is this also manually entered?  I would assume lists on pastebin and archive.org are discontinued.  Also lists that haven't been updated in X years.  I just don't know if this is populated dynamically but I would think the Updated Date would indicate when a file has last been modified in any way.

------------------------------------------------
My opinion would be to get rid of the Added date from the web interface and the publishedDate from the filterlist.json.

On the Updated date for the web page and discontinued date in the filterlist.json, either one should be used but both aren't needed and based on the date of last time the contents of the file have changed versus last time it was uploaded.

All you would be left with is the last time a list has actually changed.

I'd also make the rule count sortable as well.

**Comment by collinbarrett** [comment]
For info on the added date, see #271 . I think I agree with you that it is not info that is important enough to show in the main grid. Might consider removing it.

Updated date is the date that the file was last changed. FilterLists crawls nearly all of the lists and monitors for changes. That algorithm could still use some work (since if only the date at the top of the list is changed, FilterLists treats that as an updates).

For published and discontinued dates, those will most likely remain null for a vast majority of the lists. But, for lists where we can find that info, I think it can provide value. Published to know how long of a track record the list has, and discontinue to know if the author has discontinued it. So, I think we'll keep those fields, but I wouldn't recommend anyone assisting with updating the dataset spend too much time looking for them.

Thanks again for taking interest in the project and for assisting. In the future, feel free to open a different issue for each unique question/feedback/suggestion/etc. I don't mind a lot of issues, and it's easier to keep track of than multiple issues in the same GitHub Issue. Thanks.

**Comment by jawz101** [comment]
Thanks again.  It's a wonderful project.
