### ISSUE TITLE
dead weight

### ISSUE THREAD

**Issue by collinbarrett** [collinbarrett/FilterLists#337]
Lists who carry a lot of dead weight (URLs that are no longer live, rules that are no longer applicable) should receive a deduction in FilScore.

Inspired by #303 

**Weight:** Medium

**Comment by elypter** [comment]
this could be done by a tool that checks the urls. only for an approximate measure because some urls can be down or your host can be blocked. however there is also the risk of warning the ad networks.

**Comment by collinbarrett** [comment]
Right. Thanks. I can certainly have the FilterLists app crawl the urls. It'll be easy to implement, but with my server's limited resources, it'll take quite some time to crawl through all of the millions of urls. Which could be fine, they don't need to be crawled to frequently...

The comment on my host being blocked is valid... Not sure how to work around that on a limited budget.

Could you explain what you mean by "the risk of warning the ad networks"?

**Comment by elypter** [comment]
the blocking can be either because the ad networks or because any system detects the crawling and thinks that it is suspicious. the warning could happen if the ad networks know your ip and then check the logs for an occurence your ip. they would then know which urls and domains are on a filter list. they can do that now as well by crawling the lists themselves but this way it would appear on their logs automatically. no idea if this is a serious concern because it is really not much of a difference. im just saying this is something one should be aware of.

i think this is something that can be done but if side effects appear(which i think is not very likely) maybe reconsider.

**Comment by collinbarrett** [comment]
closing into master issue #371
