### ISSUE TITLE
EasyList TPL lists for Internet Explorer: 404 Not Found

### ISSUE THREAD

**Issue by tauxeta** [collinbarrett/FilterLists#3684]
Hi

It seems that with the exception of Peter Lowe's & Dandelion Sprout's Anti-Malware lists all the other Easylist links (including the Language-specific) are dead.

So i guess it's not unreasonable to suggest to remove them (except the two working ones) from the page.

regards

Edit: https://filterlists.com/tpl.html

**Comment by iam-py-test** [comment]
Working on a PR

**Comment by collinbarrett** [comment]
Just remove from the data json files. But, you'll have to remove any relations, too. For example, any `FilterListMaintainer.json` objects that reference the FilterList being removed.

**Comment by iam-py-test** [comment]
Of course. I'm keeping note of the filterlistids. Just wanted to make sure I was in the right place.

**Comment by iam-py-test** [comment]
PR opened.
However, given that IE is EOL and (at least on my system) just opens Edge, I don't think maintaining a page just for IE is a very high priority.

**Comment by DandelionSprout** [comment]
So, on a very quick checkup, I presumed it was just that Eyeo had taken down the `easylist-msie.(...)` domain, but it turns out that links like https://easylist-downloads.adblockplus.org/easylistchina.tpl have also been taken down by them, with no announcement of it by them that I've been made aware of, at least.

This certainly changes the playing field massively, even more so as Nordic Filters TPL is also moribund (Both because I'm on W11 and can't test on IE11 anymore, and because the TPL syntax's official documentation by Microsoft has been incomplete and entirely wrong for a decade now).

As a result, I would at least not hold objections if the Eyeo-hosted TPL lists are removed from FilterLists.

**Comment by collinbarrett** [comment]
Sounds good.

So, maybe we want to remove them from [here](https://github.com/collinbarrett/FilterLists/blob/main/web/public/tpl.html) as well.
