### ISSUE TITLE
Added column is removed

### ISSUE THREAD

**Issue by mozkan007** [collinbarrett/FilterLists#376]
Hi, I see that you removed the added column for the filters in filterlists.com. Will you bring it back? Because it is very useful to arrange the filters by their adding date. Thanks.

**Comment by collinbarrett** [comment]
Hi @mozkan007 

See conversations on this in #326 and #271 . For now, we decided to remove since it was low-value and we are trying to make room for higher value columns in the main grid.

But, we certainly could add it back if #336 is implemented.

Also, in the last few days I had to reset the production database for a variety of reasons, which reset all of the added dates to within the last few days, which isn't very helpful.

We are also actively working on [adding tags](https://github.com/collinbarrett/FilterLists/issues/65), one of which will be an auto-generated "New" tag which could in part replace this functionality.

Always open to reconsider if you have a compelling reason, but I think we won't re-add it for now.
