### ISSUE TITLE
fix Langs. filtering algorithm and use dropdown

### ISSUE THREAD

**Issue by collinbarrett** [collinbarrett/FilterLists#379]
Currently, the main grid shows the ISO 639-1 codes for the languages, but the filtering works by either the full English name of the language or the ISO 639-1 code. It is nice to be able to filter on full names, but it is not intuitive.

If I filter on "es", for example, I also get lists with just "zh" since "es" is in "Chinese".

Thoughts?

**Comment by DandelionSprout** [comment]
The easiest solution would be to make it so that the gridsearch only searches for words that _begin_ with the entered letters. After all, I don't think that anyone has ever e.g. wanted to search for something Norwegian by typing "rweg" into a search bar.

The same goes for the tag search. And while I'm at it anyway, I can just as well also suggest that the language codes and tags could be made clickable, for convenience's sake.

**Comment by collinbarrett** [comment]
Yeah, good thoughts.

I've captured click-to-filter for tags [here](https://github.com/collinbarrett/FilterLists/issues/65#issuecomment-414876385), and we'll try to address click-to-filter for langs in this issue.

**Comment by collinbarrett** [comment]
Migrated click-to-filter to #391 . This issue now remains just for fixing the filtering algorithm.

**Comment by collinbarrett** [comment]
Also convert to dropdown filter vs free-form textbox.
