### ISSUE TITLE
use Javascript obfuscation on E-mail addresses

### ISSUE THREAD

**Issue by DandelionSprout** [collinbarrett/FilterLists#405]
There are various anti-bot obfuscation methods for E-mail addresses, that aims to make it so that E-mail addresses that are posted online receive less spam. And since quite a few E-mail addresses are listed on FilterLists.com, then I propose that obfuscation methods be applied to them, so that filterlist maintainers' spam inboxes become ever so marginally slimmer.

The most advanced (and thus usually most successful) methods involve various Javascript conversion methods, for instance the ones used by https://www.albionresearch.com/misc/obfuscator.php and https://www.jottings.com/obfuscator/ (which are mutually incompatible with each other).

**Comment by collinbarrett** [comment]
Love this idea.

I've always hesitated about capturing email addresses for this reason. My thinking has typically been that the authors typically include them in plain-text in the headers of their lists (which are not obfuscated). But, some of the email addresses were captured from personal websites, GitHub profiles, etc. which may or may not have had obfuscation in place.

We could certainly add obfuscation to filterlists.com , but we'd also need to think about the plain-text versions in the json files on GitHub. If I was an email spammer, I'd probably be crawling GitHub over a niche website like FilterLists.

**Comment by collinbarrett** [comment]
Actually, we do have filterlists.com proxied through Cloudflare with their Email Obfuscation enabled.

https://support.cloudflare.com/hc/en-us/articles/200170016-What-is-Email-Address-Obfuscation-

Since the front-end is react fetching the data from an API, we need to figure out a way to verify/test that it is fairly effective against bots...

Also, since v1 and v2 of the site are still live for posterity sake (see links in GitHub readme), it'd be worth investigating those as well to make sure emails are reasonably obfuscated.

**Comment by collinbarrett** [comment]
Here's a sample from the raw html of an Email button on the V2 version of the site:

`<a href="/cdn-cgi/l/email-protection#ec9f999c9c839e98ac8d8e9c9a82c28f8381" title="Contribute to ABPVN List via email." class="button">Email</a>`

Cloudflare dynamically replaces that with the real email address using some js voodoo.

Since the current site is react fetching an API, there is no raw html email addresses, it's generated via react. I think the combination of this and Cloudflare's obfuscation makes it reasonably secure against basic bots.

That being said, the raw email addresses are still readily available in both this GitHub repo as well as via the API. If any given maintainer contacts us and asks to have their email taken down, we will certainly honor that. But, I think the value of exposing email addresses outweighs bot concerns since the maintainers made their email addresses publicly available anyway.

But, will keep this issue open a while longer to gather any further feedback.

**Comment by collinbarrett** [comment]
I just Google-ed a random sample of email addresses we have indexed (searching exact by wrapping the address in quotes). For the most part, many of the email addresses pop up in public Google search results on non-FilterLists properties.

I think we'll close this for now. We'll certainly honor requests on an individual basis to take addresses down, but, for the most part, I think the addresses we have indexed were made publicly available by maintainers already, and therefore I don't feel ethically bad about indexing them.

Certainly open to reconsider in the future, though.
