### ISSUE TITLE
I'm having problems with the Subscribe buttons

### ISSUE THREAD

**Issue by DandelionSprout** [collinbarrett/FilterLists#438]
In the past 24 hours, nothing seems to happen (i.e. no "Do you want to add this list?" message) when I click on a list's Subscribe button on FilterLists.com, and I can't seem to identify the reason for it.

The subscription links on other sites (e.g. https://adblockplus.org/subscriptions) seem to work perfectly well, so can anyone confirm that they're having problems with this as well?

**My setup:**
Software: Nano Adblocker 1.0.0.66 (Chromium version)
Browser: Google Chrome 69.0.3497.81 64-bit stable
OS: Windows 10 Pro 10.0.17134 64-bit

**Comment by hawkeye116477** [comment]
I can confirm also that subscribe links not works.

**Comment by DandelionSprout** [comment]
The three most likely possibilities that I can semi-qualifiedly guess on, are:

1) Problems with the button scripting.
2) Problems with Unicode in the links.
3) That someone (possibly ABP) suddenly thinks that FilterLists.com is an intrusive site, and has blacklisted the `abp://` protocol from working on there.

I can't confirm any of those three possibilities myself, however. I guess Collin (who lives in the US and is therefore asleep right now) could need to do some investigation on this matter when he wakes up.

**Comment by collinbarrett** [comment]
Ok, I think I know what is going on. @gorhill [has said before](https://github.com/collinbarrett/FilterLists/issues/79#issuecomment-282627707) that the script that uBlock Origin (and I guess Nano as well? I haven't used that fork at all.) uses to find the links is short-lived. If it doesn't find any subscribe links in the first few seconds, it bails.

Since I [removed the Subscribe links](https://github.com/collinbarrett/FilterLists/commit/5adf3c8fa0973f9a3e518c0bda4a33a9fe6d0bbd#diff-28e82d6a373457ff9777d47f2297ce9f) from the main grid a couple of days ago (to preserve real estate), my guess is this script bails out since it doesn't see a subscribe link quickly. I can confirm that by refreshing the page, and then clicking a "Details"->"Subscribe" very quickly. That seems to work on my end with uBO in Firefox. But, if I wait a couple seconds before clicking a "Details", the links don't work.

I think the solution will be to add at least one `abp:` link to the page ASAP so that the uBO/Nano script will hang around. I might try adding this to the raw HTML (outside of React), so as to be served ASAP, and just hide it off in a corner somewhere.

Will look into it.

**Comment by gorhill** [comment]
@collinbarrett There is a special detection case for `https://filterlists.com` in uBO: the subscribe scriplet will stick around if it finds a `<link rel="canonical" href="https://filterlists.com/">` in the DOM. So just adding this should be enough.

**Comment by collinbarrett** [comment]
Nice. That seems to have resolved it for both uBO and its fork Nano in Chrome and Firefox on Windows.

@DandelionSprout and @hawkeye116477 , please confirm.

**Comment by DandelionSprout** [comment]
Seems to work on my end now, so I guess I can confirm.

**Comment by hawkeye116477** [comment]
Yes, works perfectly :smile:.

**Comment by collinbarrett** [comment]
Great, thanks for the feedback.
