### ISSUE TITLE
Add or evaluate GoodbyeAds by Jerryn70

### ISSUE THREAD

**Issue by Atavic** [collinbarrett/FilterLists#444]
## Feature Request: Adding List

Goodbye Ads is Specially Designed for Mobile Ad Protection: https://github.com/jerryn70/GoodbyeAds
Telegram : https://t.me/GoodbyeAds
XDA : https://forum.xda-developers.com/android/software-hacking/goodbye-ads-advanced-protection-ads-ad-t3827269

...an attempt at setting some ids follows:

License: MIT
name GoodbyeAds
viewUrl https://raw.githubusercontent.com/jerryn70/GoodbyeAds/master/Hosts/GoodbyeAds.txt
permissiveAdaptation Yes
permissiveCommercial Yes
maintainerId Jerryn70 (XDA Senior Member)
mergeFilterListId No
upstreamFilterListId No
Software: Adaway, DNS66, BLOKADA, Hostsman
syntaxId: Hosts file, using 0.0.0.0 format

**Comment by DandelionSprout** [comment]
I'll be adding this list to my Friday pull request, but I think I'd just point out that mentioning the list's licence (which in this case is MIT) is normally preferable to mentioning the licence's attributes ("permissiveAdaptation" and "permissiveCommercial"), since FilterLists auto-ties the licence to the licence's attributes.

**Comment by collinbarrett** [comment]
Thanks all!

One note about why I added `permissiveAdaptation` and `permissiveCommercial` to the data model at all is to honor licenses if something like #8 were to ever be implemented.
