### ISSUE TITLE
add Norsk Adblockliste AdGuard fork

### ISSUE THREAD

**Issue by collinbarrett** [collinbarrett/FilterLists#478]
https://github.com/AdguardTeam/FiltersRegistry/blob/master/filters/ThirdParty/filter_120_NorskAdblockliste/filter.txt

AdGuard-compatible fork of now offline http://home.fredfiber.no/langsholt/adblock.txt

**Comment by DandelionSprout** [comment]
This list is 4 years old and only had 2-ish revisions, and that shows. From my effort at incorporating that list into my Norwegian list, around 80% of the entries didn't do anything (as of late 2017), and more than ⅓ of the URLs were dead. A select few of the entries also have high levels of bizarrity to them (such as `||ads.nrk.no^`, since NRK is an ad-free public media environment).

My personal standpoint is that that list would be better off if it was forgotten by mankind, but I also acknowledge that you like to take care of practically every list that has ever existed, so I guess it'd be wrong of me to stop you from doing it.

**Comment by collinbarrett** [comment]
lol, I appreciate your feedback. I think we can forget it, since the original is offline, the mirror is over 4 years old, and based on what you said about the quality. If you (as a Norwegian maintainer) find it generally useless, I can't imagine anyone else finding any value in it.
