### ISSUE TITLE
Software support

### ISSUE THREAD

**Issue by collinbarrett** [collinbarrett/FilterLists#50]
Use the list's software support to calculate the FilScore.

Lists that can be subscribed to in larger numbers of software tools should be rated slightly better.

Requires #11

**Comment by elypter** [comment]
i think those should be split in filters that have cosmetic elements and those which dont. otherwise all cosmetic filters would score bad. i think pure domain filters have the advantage of being easier on resources and should get a higher score but it might be a better choice to base that on syntax usage.

**Comment by collinbarrett** [comment]
thanks for the feedback. I think I agree with you. need to think on it a bit more.

**Comment by collinbarrett** [comment]
Yeah, I don't think this factor should be considered at all anymore. A list targets a syntax. It's not the list's fault if the syntax it targets isn't supported by more software packages.
