### ISSUE TITLE
"Tags" text field doesn't work

### ISSUE THREAD

**Issue by DandelionSprout** [collinbarrett/FilterLists#509]
I'm trying to type various search terms into the `Tags` field, but nothing shows up and no search filtering takes place. I'm struggling with this on both Chrome and Edge. Can you (guys?) confirm this problem on your ends?

Oh, and while I'm at it anyway: Would it be possible to make it so that the `Tags` headline button can be clicked on to sort (like what can be done with the `Name` and `Updated` buttons), e.g from most to fewest tags, so that it becomes much easier for me to see which lists that haven't been given any tags yet?

![image](https://user-images.githubusercontent.com/22780683/45921435-b9c73b80-beb5-11e8-92fc-48733f5edaf2.png)

**Comment by DandelionSprout** [comment]
I am also hoping that when such a high-priority bug (or so I think it is) is fixed, that it'd be reason enough to trigger a faster-than-usual refresh of the API, leading to AdBlock no longer being shown as supporting domains lists.

This is important because I plan to open an issue ticket at AdBlock's support pages, which among other things will suggest that they can replace or supplement their extension settings' link to https://adblockplus.org/en/subscriptions with https://filterlists.com/. And I think they'd raise some eyebrows if AdBlock was shown on FilterLists as supporting lists that it doesn't actually support.

¹ = Replacing 3 discontinued lists and 4 HTTP links; and to add my Norwegian list to AdBlock.

**Comment by collinbarrett** [comment]
Caused by my work on #505 . Still working out the kinks in my testing process (thus the breakage). Will address ASAP.

Hmm, not sure if sorting by number of tags makes sense intuitively. Not opposed to it. Just trying to make things as intuitive as possible. Is it common for other similar tables on the web to sort by number of items in the field? I guess sorting alphabetically doesn't make a lot of sense. So, if sorting is enabled, by tag count could make sense...

Part of the issue for the long caching currently is that the API queries are really inefficient. I have learned a lot from the first go of it, and am working on cleaning these all up for #505 . Once I verify that performance has been improved in generating responses, I'll certainly drop the caching way back down to improve data freshness.

I'd love for filterlists.com to be pointed to from software's pages like AdBlock's. That'd be awesome.

**Comment by collinbarrett** [comment]
related to #428

**Comment by DandelionSprout** [comment]
Okay, here goes: 
![image](https://user-images.githubusercontent.com/22780683/45935627-764ff880-bfad-11e8-8a34-75cff13f1293.png)

PS: Apparently, tickets for AdBlock are meant to be private, so it appears to me that I can't properly link to it. Or, sure, I could link to https://help.getadblock.com/support/tickets/55558, but I currently presume that the link won't really work.

**Comment by collinbarrett** [comment]
Cool. Hopefully FilterLists is to the point where it merits a bit more attention by the adblock community. I haven't pushed marketing it a whole lot until I thought it was truly a helpful tool, but I think we are approaching that subjective milestone. There is certainly still a lot we want to improve, but it is valuable enough to market a bit.

In the publicity realm, it was also just added here: https://builtwithdot.net/project/125/filterlists
