### ISSUE TITLE
support filtering out discontinued lists

### ISSUE THREAD

**Issue by dimqua** [collinbarrett/FilterLists#522]
Could you please add a checkbox (for example) to hide discontinued lists?

**Comment by collinbarrett** [comment]
I didn't exactly implement your request, but now the "Updated" column (toggle on via the checkboxes below the table) shows the `discontinuedDate` for the list if we have one, since that should be approximately the last time the list was updated. So, you still can't filter discontinued out from the grid, but you can sort by the Updated column putting those that have been discontinued at the end.

If you still think the original request would be helpful, feel free to provide further feedback and we can consider re-opening.

**Comment by collinbarrett** [comment]
Related to #427 and #528
