### ISSUE TITLE
add support for toxic_domains list

### ISSUE THREAD

**Issue by KonoromiHimaries** [collinbarrett/FilterLists#577]
## Adding or Updating Lists?

https://www.stopforumspam.com/downloads

**Comment by DandelionSprout** [comment]
I had previously been unaware that StopForumSpam had domain versions á la https://www.stopforumspam.com/downloads/toxic_domains_whole.txt, so that was actually a great find. 👍 

But I'm waiting out on adding your recentmost suggestions, both in expectation of #372, and because I've grown slightly tired of having to cobble together all the needed information myself, especially as I've had to spend some of my energy this week on dealing with translations and PC upgrades. It's not too difficult to make pull requests to add lists like these, and I'm confident that Collin would've appreciated the effort and would be more than happy to correct any theorethical syntax mistakes.

**Comment by collinbarrett** [comment]
Agreed. Still feel free to open issues for new lists, @KonoromiHimaries , that's great. But, PRs are even better.

I try to focus my time on features. @DandelionSprout has been a tremendous help on maintaining data, but I know #372 is really needed. It's just a big undertaking, and I'm not sure the best approach yet.

**Comment by bogachenko** [comment]
@KonoromiHimaries @DandelionSprout and it should be added all at once? I mean there the file is toxic_domains_whole_filtered.txt is limited only to them? or how?
![default](https://user-images.githubusercontent.com/8535285/51447804-8a1c2900-1d19-11e9-8c6a-f9b4971fbf21.png)
