### ISSUE TITLE
update URLs of Nano Defender Integration

### ISSUE THREAD

**Issue by MS-PC** [collinbarrett/FilterLists#592]
## Adding or Updating Lists?

Current:
```
"viewUrl": "https://raw.githubusercontent.com/NanoAdblocker/NanoFilters/master/NanoMirror/NanoDefender.txt",
"viewUrlMirror1": "https://raw.githubusercontent.com/jspenguin2017/uBlockProtector/master/uBlockProtectorList.txt",
"viewUrlMirror2": "https://cdn.rawgit.com/NanoAdblocker/NanoFilters/master/NanoMirror/NanoDefender.txt"
```

Changed:
```
"viewUrl": "https://raw.githubusercontent.com/NanoAdblocker/NanoFilters/master/NanoMirror/NanoDefender.txt",
"viewUrlMirror1": "https://cdn.rawgit.com/NanoAdblocker/NanoFilters/master/NanoMirror/NanoDefender.txt"
```

Once I proposed updating the list for the reasons that are in this issue: #345

**Comment by collinbarrett** [comment]
related to #585

**Comment by collinbarrett** [comment]
will see if @DandelionSprout can chime in on this one. I'm not super well versed in the nano lists...

**Comment by DandelionSprout** [comment]
I can understand why MS-PC would want to remove that link, since I now know that `https://raw.githubusercontent.com/jspenguin2017/uBlockProtector/master/uBlockProtectorList.txt` lacks a lot of in-list metadata tags for reasons that I'm not fully sure about, which I didn't know about when I added the link.

But also, I interpreted https://github.com/NanoAdblocker/NanoCore/issues/220#issuecomment-430673998 as that Jspenguin2017 plans to replace his Rawgit list links with GitCDN ones, although such a change has not been applied to https://github.com/NanoAdblocker/NanoCore2/blob/master/src/assets.json at the time of writing.

I am inclined to support MS-PC's position on this and to remove that link as it currently stands; although I currently expect that Jspenguin will do some changes to some of his list links quite soon, so that at least I wouldn't have done any hasty changes, if I was the one who'd make the pull for this. Feel free to remove the link right now if any of you (or someone else) will be making the pull.

**Comment by jspenguin2017** [comment]
> will see if @DandelionSprout can chime in on this one

Why not just ask the person who knows the answer? 

> lacks a lot of in-list metadata tags

That file exists for legacy reasons, and is currently read by other build scripts to insert metadata. 

And no, having proper headers doesn't mean it works with AdGuard. 

> replace his Rawgit list links with GitCDN ones

Yes, I'm still thinking about how to deal with legacy subscriptions. I'll probably add a notification in Nano Defender extension. 

I was at school for over 12 hours yesterday because an exam was scheduled at 7 PM... And I also have quite a bit of homework to catch up on. I'll certainly update the links, but we still have a year to do it, so no rush.
