### ISSUE TITLE
remove/update some dead links

### ISSUE THREAD

**Issue by bogachenko** [collinbarrett/FilterLists#612]
so,
I was bored. And I scrolled your site and found deleted/renamed?/inaccessible pages with filters.
I'm on page 40 now.
are we going to fix this?

~1Hosts = https://1hosts.cf~
~1Hosts (Domains) = https://1hosts.cf/complete/list.txt~
~1Hosts Mini = https://1hosts.cf/mini/~
~1Hosts Mini (Domains) = https://1hosts.cf/mini/list.txt~
ABP Anti-Circumvention Filter List - Arabic  = https://raw.githubusercontent.com/abp-filters/abp-filters-anti-cv/master/arabic.txt
ABP Anti-Circumvention Filter List - Bulgarian = https://raw.githubusercontent.com/abp-filters/abp-filters-anti-cv/master/bulgarian.txt
ABP Anti-Circumvention Filter List - Hebrew = https://raw.githubusercontent.com/abp-filters/abp-filters-anti-cv/master/hebrew.txt
ABP Anti-Circumvention Filter List - Indonesian = https://raw.githubusercontent.com/abp-filters/abp-filters-anti-cv/master/indonesian.txt
ABP Anti-Circumvention Filter List - Latvian = https://raw.githubusercontent.com/abp-filters/abp-filters-anti-cv/master/latvian.txt
ABP Anti-Circumvention Filter List - Lithuanian = https://raw.githubusercontent.com/abp-filters/abp-filters-anti-cv/master/lithuanian.txt
ABP Anti-Circumvention Filter List - Romanian = https://raw.githubusercontent.com/abp-filters/abp-filters-anti-cv/master/romanian.txt
~abuse.ch Feodo BadIP Blocklist = https://feodotracker.abuse.ch/blocklist/?download=badips~
~abuse.ch Feodo Domain Blocklist = https://feodotracker.abuse.ch/blocklist/?download=domainblocklist~
~abuse.ch Feodo IP Blocklist = https://feodotracker.abuse.ch/blocklist/?download=ipblocklist~
AntiPubWeb = http://www.antipubfirefox.org/antipub/antipubfirefox-adblocklist-current-expanded.txt
~Ayucat Powerful List = http://www.antipubfirefox.org/antipub/antipubfirefox-adblocklist-current-expanded.txt~
~CoinBlocker IPs List = https://zerodot1.gitlab.io/CoinBlockerLists/MiningServerIPList.txt~

~and this #611 of course~

**Comment by Atavic** [comment]
1Hosts = https://1hos.cf/
Related: https://github.com/collinbarrett/FilterLists/issues/539

ABP Anti-Circumvention Filter List = https://github.com/abp-filters/abp-filters-anti-cv

abuse.ch Feodo gives Error 503 first byte timeout, maybe a temporary issue?

...

CoinBlocker IPs List: https://zerodot1.gitlab.io/CoinBlockerListsWeb/downloads.html

**Comment by collinbarrett** [comment]
Related to #21 planned eventually.

Thanks for finding these. PRs welcome against [data ](https://github.com/collinbarrett/FilterLists/tree/master/data) if anyone is able to help implement.

**Comment by DandelionSprout** [comment]
I'll work on a pull to change the 1hosts URLs to 1hos.cf.

The issue with those seven Anti-Circumvention lists is that they're empty. It seems to me that ABP pre-emptively made such lists as an equivalent to almost all of ABP's officially acknowledged lists... even if there were no entries in some of the languages. Several more of those lists are also oddly short: The Danish such list has only 2 entries.

The Feodo lists were conspicuously empty for several months, so I wouldn't be surprised if they just as well deleted them for good measure. I can attempt to delete those lists, seeing as they had no previous worth that I'm personally aware of.

AntiPubWeb went offline in August-ish, projected a reinstatement in September on the maintainer's blog, and I haven't looked into the matter since then.

CoinBlocker seems to have moved to a regular GitLab domain (https://gitlab.com/ZeroDot1/CoinBlockerLists). I can attempt to fix the URLs of the seven lists, and will see if I'm able to add the new uBO version.

**Comment by DandelionSprout** [comment]
As an additional note, it appears that the IP version of his list has been changed into a paid on-request service, so I guess that this list is not worth keeping anymore.

**Comment by collinbarrett** [comment]
closed by https://github.com/collinbarrett/FilterLists/commit/b3017fc7e041185a134a25f840fbb8e425c8d753
