### ISSUE TITLE
Finnish list has Japanese listed as language

### ISSUE THREAD

**Issue by theel0ja** [collinbarrett/FilterLists#631]
<img width="757" alt="screen shot 2018-11-29 at 22 56 24" src="https://user-images.githubusercontent.com/5832930/49251441-0b49f480-f42a-11e8-9bc4-0e8b6f5c2a87.png">

Offtopic: https://www.yamagata-europe.com/en-gb/blog/the-finnish-japanese-connection

**Comment by DandelionSprout** [comment]
You see, there's quite a lot of numerical, nearly-non-descript values and different .json files that a pull request maker for FilterLists have to keep track of. Therefore it unfortunately often happens that I don't get things 100% right. For that matter, I also managed to give *ABPindo* the language tag of Malagasy (as in what they speak on Madagascar) instead of Malaysian.

I'll get around to make an extra pull to correct these two things, after I've done some basic house duties and grocery shopping tonight.

**Comment by bogachenko** [comment]
close?

**Comment by theel0ja** [comment]
seems to be fixed
