### ISSUE TITLE
The site isn't updating

### ISSUE THREAD

**Issue by DandelionSprout** [collinbarrett/FilterLists#651]
I just wanted to point out quickly, that it doesn't appear to me that #648 and #650 has taken effect on [FilterLists.com](https://filterlists.com/) yet, and that the list counter still shows 1,212 lists, which I recall was what it showed a week ago.

Is this possible to fix?

**Comment by collinbarrett** [comment]
possibly related to #636 . I have some ideas. might take me a day or two to look at. thanks.

**Comment by collinbarrett** [comment]
also possibly related to #137

**Comment by collinbarrett** [comment]
Fixed by https://github.com/collinbarrett/FilterLists/commit/4e06b124a36a9071a0a4e0808d93b057e25d5b6d and https://github.com/collinbarrett/FilterLists/commit/846ae105ecb45c4ec037dc27168d73d27c7e9040 for now.

Still need to resolve #636 and #137 eventually, but this should get the site updating again.

Thanks for your patience. Hoping to get back to more active work on this project. Just changed jobs and did a bunch of traveling the last month or two.

**Comment by DandelionSprout** [comment]
Ah, so that's why you were mostly gone. Sounds like a good enough reason to me.

I've been banking on #263 and #372 to be resolved before I could do the next major contributions I have in mind, so in the meantime I've mostly only added some lists and a few tags. But I'm in no position to push you too hard on it, so here's hoping that the globetrotting went well. 🌍
