### ISSUE TITLE
preserve state of filters/sorts

### ISSUE THREAD

**Issue by yfdyh000** [collinbarrett/FilterLists#715]
I just went through the site for the first time. When I clicked a button from "Details"  to view information, it opened the external page to overwrite the current page, which made me a bit surprised and had to go back and possibly lose the existing searches. That being said, the use of the `_blank` seems to be a bit controversial and risky.

The footer links has the same issue, it overwrite the main page.

**Comment by collinbarrett** [comment]
Yeah, this is a great point I'd love to address. I have read articles about setting `target="_blank"`is potentially poor UX practice and actually was a security issue for a bit as well.

The ideal solution would be to save a bit of anonymous state information in the browser as a cookie. Nothing we would use to collect or track visitors, but just something so that if they returned back to FilterLists it would preserve the same state of the filters/column sorts.

For now, you can always use the `ctrl+click` or `cmd+click` depending on the browser/OS to open links in new tabs.

Will keep this open to maybe address the cookie idea in the future.

**Comment by collinbarrett** [comment]
In the new UI, we are using `_blank` for all external links. However, we also use `rel="noopener noreferrer"` to mitigate [the security risks](https://developers.google.com/web/tools/lighthouse/audits/noopener).

I think the new drawer-based UI for details makes it a bit easier to navigate without losing state of filters/sorts.

I'm going to close this for now, but feel free to leave further comments and we can reconsider.

Thanks.
