### ISSUE TITLE
Make various changes to vendor.css (or make it editable)

### ISSUE THREAD

**Issue by DandelionSprout** [collinbarrett/FilterLists#743]
Now that I have a modicum of understanding of how .tsx files and FilterLists' bootstrapper works, I propose a handful of significant changes to `vendor.css`, a file that is hosted on [the filterlists.com domain](https://filterlists.com/dist/vendor.css) but which currently doesn't appear to be hosted in this repo, and thus I'm now asking for you to do the desired changes to the file, or to host(/fork?) it on this GitHub repo.

Although it can't be called a local build per se, I did experiment by downloading the site in HTML form through Chrome and then editing its `vendor.css` in various ways.

### Make the website use the whole screen width on desktops:

The part early in line 4 that says `.container{width:100%;(…);margin-left:auto}@media(min-width:576px){.container{max-width:540px}}@media(min-width:768px){.container{max-width:720px}}@media(min-width:992px){.container{max-width:960px}}@media(min-width:1200px){.container{max-width:1140px}}`, should be changed to `.container{max-width:98vw!important;width:100%;(…);margin-left:7px}`.

This is a similar to a fix that has been in [Dandelion Sprout's Website Stretcher](https://raw.githubusercontent.com/DandelionSprout/adfilt/master/Dandelion%20Sprout's%20Website%20Stretcher.txt) for some time by now.

### Make the site loadable in Internet Explorer:

Apparently, adding ` <script src="https://cdn.polyfill.io/v2/polyfill.min.js"></script>` somewhere in `vendor.css`, for example at the bottom of the file, makes the site fully loadable in IE11.

### Add more button classes:

This request is not set in stone, but I'd quite like for the possibility to add more button classes to it. For example, I was originally planning to differ between .onion HTTP and .onion HTTPS list links in https://github.com/collinbarrett/FilterLists/pull/742, until I discovered that there were no light-green buttons defined in `vendor.css`. So if I want to do some changes to FilterLists' link buttons (I have some ideas for the *View* buttons planned within the next week-ish), being able to set new classes and colours would've been awesome.

**Comment by collinbarrett** [comment]
So vendor.css is primarily composed of bootstrap's css. It's compiled during the webpack build (see [here](https://github.com/collinbarrett/FilterLists/blob/c1eb75e4bc0a677bca2cceb9af9500ed4983e1fe/src/FilterLists.Web/webpack.config.vendor.js#L6)). We should be able to add additional css to [`site.css`](https://github.com/collinbarrett/FilterLists/blob/master/src/FilterLists.Web/ClientApp/site.css), though.

**Comment by DandelionSprout** [comment]
Having just woke up, and tested adding the first two categories to `site.css` instead, this went far better than I expected at first sight. I'll edit #744 accordingly.

**Comment by DandelionSprout** [comment]
Now that I know the ideal way to work around this issue, I'd consider it to be resolved now.

**Comment by existential-fallacy** [comment]
Hello to you all. I’m writing here to let you know that lancelot-moon generally behaved in a pushy, angry, and “everyone’s wrong but me” way while I was an active contributor to AfGuard Pro via their beta campaign. I’m telling you this now so that if you even sniff out his starting that way here from miles away, I’d seriously consider:

1. An incredibly strong warning.
2. Since (1.) will fail, and it will, disallowing opening any issues not directly related to any filters he creates (from knowledge of ~2 years ago, he did one for personal use only, though that may have changed.)

This person has an ego larger than the Chef’s as he believes himself to be the sole reason AdGuard is known in Taiwan. Moreover, this is something he repeatedly bragged/lied about openly and constantly within the AdGuard iOS beta repo that those of us who helped out used for civil discussion, ideas, etc. Andrey made it clear that AdGuard being used in Taiwan has nothing to do with anything but AdGuard and en masse, slow word of mouth & Internet forums. Andrey especially laughed off and dismissed this person’s claim as he knew it to be patently false,

Be ready for conflict if he begins “contributing” to the FilterLists.com repository. You have been warned (I never really liked that phrase very much, but it’s quite fitting in this context.)

**Comment by DandelionSprout** [comment]
I appreciate the warning, except it's very wildly off-topic, in addition to that user not having made any visible contributions to anything outside of AdGuard. As the situation currently stands, I think that sending an E-mail to Collin would've been preferable to posting about it in this thread.
