### ISSUE TITLE
Site lies about 3rd-party javascript

### ISSUE THREAD

**Issue by Tanath** [collinbarrett/FilterLists#751]
Visiting filterlists.com with js disabled says:

> We do not use any third-party JavaScript, and your privacy is very important to us. 

Yet there's a script from `cdn.polyfill.io`.

**Comment by collinbarrett** [comment]
Ah, good catch. That was added by @DandelionSprout very recently [here](https://github.com/collinbarrett/FilterLists/commit/1708826e4d4d0536088954f285dadbc1df114757#diff-927cb9e541b974800379982bbbfda7ff).

@DandelionSprout, can you remind me why that was added, and we can see about fixing that potential privacy issue? Thanks.

**Comment by DandelionSprout** [comment]
It was added in a(n ultimately failed) attempt to get the site to load in Internet Explorer 11, as a quick Google search told me that such a polyfill script was the by far easiest solution to get around the "Promise is undefined" error.

However, after the script was added, it turned out that IE11 [was still throwing a fit](https://github.com/collinbarrett/FilterLists/pull/744#issuecomment-480456102) about a dozen different JS elements, so I guess that the polyfill script can be removed for now if needed.

**Comment by DandelionSprout** [comment]
Additionally, since polyfill.io was an MIT-licenced open-source project whose domain's frontpage has virtually zero tracking (apart from two fonts originating from Financial Times), I thought at the time that it surely couldn't be a matter of life or death to use it for testing purposes.

**Comment by DandelionSprout** [comment]
Since #751 was doomed from the start, that leaves us with two options:

1) Clone https://cdn.polyfill.io/v3/polyfill.min.js and host it on the FilterLists.com domain (Note that this'd use v3 of the JS file, instead of the v2 that I had previously used).
2) Remove the JS link altogether.

I'm honestly not sure which option would be preferable, so I'll leave it to Collin to decide.

**Comment by collinbarrett** [comment]
I'd say let's remove the link altogether (2). I don't think it's super important for FilterLists to support Internet Explorer (whose latest and final release was 6 years ago).

**Comment by collinbarrett** [comment]
closed by #753
