### ISSUE TITLE
Update some AdGuard filters' names.

### ISSUE THREAD

**Issue by lancelot-moon** [collinbarrett/FilterLists#755]
AdGuard English Filter
-> AdGuard Base Filter

AdGuard Spyware Filter
-> AdGuard Tracking Protection Filter

AdGuard Useful Ads Filter
-> AdGuard Filter unblocking search ads and self-promotion

**Comment by existential-fallacy** [comment]
These names are not universal. They exist and are “updated” / changed from their original names that are still in use. If AdGuard wishes to change the names of their filters so that they `conflict` with what they are named right here on GitHub, then by all means Andrey has the right to do so. However, as an individual who does not represent AdGuard in any way whatsoever, @lancelot-moon Unless you were sent here on request by any of the AdGuard devs with sufficient rights to do so, I do not feel this is an appropriate issue. Nor do I think this is, for lack of a better phrase, ‘Good GitHub Behaviour”.
![BA59E7B8-EB02-41B4-98CF-EF1AD30224BA](https://user-images.githubusercontent.com/48530673/56071732-2d4f6e00-5d5e-11e9-96b2-5bdba10ff98a.jpeg)
![A065EFF1-FF27-4C62-93CD-8CFAB4BC3BC6](https://user-images.githubusercontent.com/48530673/56071733-2d4f6e00-5d5e-11e9-94b4-13849540f706.jpeg)

**Comment by bogachenko** [comment]
@existential-fallacy You are not right.

@lancelot-moon I'll do PR now

**Comment by lancelot-moon** [comment]
@existential-fallacy
AdGuard early renamed these filters.
Just you don't know because you may not use AdGuard products.
Try its free AG Browser Extension.

AdGuard team only don't update its KB.
<details><summary>Screenshots:</summary>

![image](https://i.imgur.com/cAYH9yz.png)

![image](https://i.imgur.com/CplYKoP.png)

![image](https://i.imgur.com/4TsJdya.png)
</details><br/>

**Comment by existential-fallacy** [comment]
@bogachenko If you’d kindly direct me to the _Repository_ - not the software for any platform  - that labels it as AdGuard Base Filter, I’d appreciate it just for my own enlightenment. “Just screenshots” were just taken and here’s another with EST up top. ✌🏼
![F5FDDF94-52B1-4117-8A46-33809B6A9521](https://user-images.githubusercontent.com/48530673/56072484-60493000-5d65-11e9-8e4d-de6cda165d65.png)

**Comment by lancelot-moon** [comment]
Absolutely you're not an AdGuard user.
Those filters were early renamed in every AdGuard product.

Press, pull down and then release on the filters section's screen of AG for iOS.

Those filters information will be sync and updated with AdGuard server.

**Comment by lancelot-moon** [comment]
@existential-fallacy
After I mentioned, Andrey assigned TheHasagi to modify the filters' names.

You should shut up because you may be even not an AdGuard user.

**Comment by existential-fallacy** [comment]
> @existential-fallacy
> After I mentioned, Andrey assigned TheHasagi to modify the filters' names on KB.
> Just AdGuard team are busy in fixing AdGuard apps' bugs.
> 
> You should shut up because you may be even not an AdGuard user.

Hostile as usual. I’m out. I don’t need that sort of energy. Especially polluting a love of mine. Goodnight all.

**Comment by lancelot-moon** [comment]
Such an ignorant guy and always don't admit your mistake.
Officially, AdGuard had modified those filters' names.
https://github.com/AdguardTeam/FiltersRegistry/issues/159
