### ISSUE TITLE
I have a question in Malvertising filter ?

### ISSUE THREAD

**Issue by Evanju1** [collinbarrett/FilterLists#772]
![disconnect](https://user-images.githubusercontent.com/49491405/56899186-0d89ab00-6abd-11e9-93fb-4f38e6348f85.png)

whether the all ads google, yahoo , facebook , aol ? is malicious ?
that I actually found this ad to be a safe ad because there was no evidence that this ad caused phishing or malware

then where is the difference with the adguard spyware filter ? 
or maybe they better change their name

**Comment by DandelionSprout** [comment]
As a long-time (≥18 months) user of *Malvertising filter list by Disconnect*, I can tell that it's pretty trigger-happy and broadly blocking. As to why they chose that name, that's something that I think should be more fittingly brought up with the Disconnect team, and not with us; although part of their reason seems to be to distinguish it from [their regular-ads-only list](https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt).

*AdGuard Spyware Filter* (now named *AdGuard Tracking Protection Filter*) attempts to block trackers instead of ads or malware, so those two lists are hardly comparable at all.

**Comment by collinbarrett** [comment]
Closing for now as not directly related to the FilterLists app, but please feel free to continue to discuss. I don't personally have any insight on the question.
