### ISSUE TITLE
Add Web Annoyances Ultralist

### ISSUE THREAD

**Issue by yourduskquibbles** [collinbarrett/FilterLists#94]
Hi,

Do you take filter list add requests? I thought maybe it would be helpful to some people if they knew my list existed, the purpose is the following:

```
Purpose is to block annoying web elements and make the web more user friendly!
Reclaim lost screen real estate by blocking sticky web elements.
Cosmetically removes and/or keeps elements locked to a fixed location.
When possible, sticky headers, stickynavs, and stuck headers will be pinned to the top of the site to prevent site breakage.
Works against scrolling headers, stickynavs, sticky headers, floating headers, social share bars, smartphone app banners, app download nag screens, floating navigation boxes, jump to top, site overlays, subscription nags and generally annoying website behavior. 
Works best with uBlock Origin.
```

The project is [located on github](https://github.com/yourduskquibbles/webannoyances)

[Raw filter list location](https://raw.githubusercontent.com/yourduskquibbles/webannoyances/master/ultralist.txt)

Thank you for your time!

**Comment by bershan2** [comment]
@yourduskquibbles It would be nice if you could compose the entry yourself (since you know this list best as you are its author). Here is something to start with:

Your description is fairly long and the first two sentences are too generic to be meaningful. Also I modified the first sentence a bit.

```
{
  "descr": "Cosmetic filter for removing or locking location of web annoyances. When possible, sticky headers, stickynavs, and stuck headers will be pinned to the top of the site to prevent site breakage. Works against scrolling headers, stickynavs, sticky headers, floating headers, social share bars, smartphone app banners, app download nag screens, floating navigation boxes, jump to top, site overlays, subscription nags and generally annoying website behavior. Works best with uBlock Origin.",
  "descrSourceUrl": "https://github.com/collinbarrett/FilterLists/issues/94",
  "donateUrl": "Do you have it?",
  "email": "Do you have it?",
  "forumUrl": "Do you have it?",
  "homeUrl": "https://github.com/yourduskquibbles/webannoyances",
  "issuesUrl": "https://github.com/yourduskquibbles/webannoyances/issues",
  "list": "Web Annoyances Ultralist",
  "tagLang": ["en"],
  "viewUrl": "https://raw.githubusercontent.com/yourduskquibbles/webannoyances/master/ultralist.txt"
}
```

The lists properties are described in [README](https://github.com/collinbarrett/FilterLists/blob/master/README.md). Please confirm correctness of above information and either fill out or remove `"donateUrl"`, `"email"`, and `"forumUrl"`.

P.S.: What do you mean by "Works best with uBlock Origin."? Does it utilize uBO syntax or do you simply recommend uBO as the most efficient extension?

**Comment by yourduskquibbles** [comment]
@bershan2 thanks for the comments - I will submit a pull request soon.

**Comment by bershan2** [comment]
@yourduskquibbles Neat.

**Comment by collinbarrett** [comment]
I've been really busy lately. If you can create a pull request adding your list to the [list data file](https://github.com/collinbarrett/FilterLists/blob/master/data/lists.json), I can implement quicker. Thanks!
